#!/bin/bash

# TODO: replace these with a more intelligent
# include system for our use cases
#source ./distro
#source ./install

# Make sure only root can run our script
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

check_or_install_git() {
    # TODO: Abstract out OS specific details.
    command -v git >/dev/null || { apt-get update -y; apt-get install -y git; }
}

fetch() {
    local repo=$1

    local git="git:(.*)"
    local s3="s3:(.*)"

    if [[ $repo =~ $git ]];
    then
       path="${BASH_REMATCH[1]}"
       git clone "$path"
    fi
}

goto_dir() {
    cd $1
}

run_command() {
    command=$1

    $($command $@)
}

parse_args() {
    repo=$1
    shift
    basename=${repo##*/}
    basename=${basename%.*}

    command=$1
    shift
}

repo=$1
shift

# this extracts the fetched subdirectory name after a clone
basename=${repo##*/}
basename=${basename%.*}

command=$1
shift

check_or_install_git
fetch $repo
goto_dir $basename
run_command $command $@
